### ISSUE TITLE
Replace CurrentBook with Book

### ISSUE THREAD

**Issue by jrodonohue** [CS495Group8/ByItsCover#6]
The work on the scraping branch is mostly great, but the `CurrentBook` idea seems like it could be improved by using a `Book` class instead and passing it to objects which need it. Some reasons for this are the following:

- Representing multiple books at once is necessary (e.g. processing a list of search results from the scraper)
- Synchronized access to a singleton is complicated, and returning an instance is simpler.
- I can't think of any scenario where a singleton is helpful, and it is natural for hypothetical procedures such as `DisplayReview` to take a book as a parameter.

**Comment by mtuthill** [comment]
Completed and merged by @jrodonohue
