### ISSUE TITLE
Replace deprecated AsyncTask with futures

### ISSUE THREAD

**Issue by jrodonohue** [CS495Group8/ByItsCover#7]
Unfortunately, the Android API is a bit of a mess, and `AsyncTask` is [deprecated](https://developer.android.com/reference/android/os/AsyncTask). According to the API documentation, there are some weird behaviors and inconsistencies. It would probably be easier to use [futures](https://developer.android.com/reference/java/util/concurrent/Future) to do all of our asynchronous processing.

**Comment by mtuthill** [comment]
Completed and merged by @jrodonohue
